apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- minimal-notebook-imagestream.yaml
- generic-data-science-notebook-imagestream.yaml
- minimal-gpu-notebook-imagestream.yaml
- pytorch-notebook-imagestream.yaml
- tensorflow-notebook-imagestream.yaml
- trustyai-notebook-imagestream.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
