name: Image Stream Updater
on:
  workflow_dispatch:  # for manual trigger workflow from GH Web UI
    inputs:
      hash:
        required: true
        description: "git hash"
      branch:
        required: true
        description: "Release branch that we want to affect"
jobs:
  modify-yaml-file:
    runs-on: ubuntu-latest

    steps:

      - name: Fetch git hash from the user
        if: github.event.inputs.hash != ''
        run: echo "Git hash ${{ inputs.hash }}"

      - name: Get Branch from the user
        if: github.event.inputs.branch != ''
        run: echo "Release branch name ${{ inputs.branch }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Install skopeo
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo

      - name: Fetch the latest tag name from the MINIMAL based on git hash
        shell: bash
        id: latesttag
        run: echo "latesttag=$(skopeo inspect docker://quay.io/opendatahub/workbench-images:base-ubi9-python-3.9-2023a-weekly | jq .RepoTags | grep -E jupyter-minimal-ubi9-python-3\.9-2023a-\[0-9]+-${{ inputs.hash }} | head -n 1 | sed 's/[,"[:space:]]//g')" >> ${GITHUB_OUTPUT}

      - name: Provide me it in digest format
        shell: bash
        env:
          LATEST_TAG: ${{ steps.latesttag.outputs.latesttag }}
        id: digest
        run: |
         echo "digest=$(skopeo inspect docker://quay.io/opendatahub/workbench-images:${{ env.LATEST_TAG }} | jq .Digest | sed 's/sha256/quay.io\/opendatahub\/workbench-images@sha256/g')" >> ${GITHUB_OUTPUT}

      - name: Modify the first image stream
        shell: bash
        env:
         DIGEST: ${{ steps.digest.outputs.digest }}
        run: |
         yq e '.spec.tags[0].from.name = "'"$(echo ${{ env.DIGEST }} | sed 's/\"/\//g')"'"' -i notebook-images/base/minimal-notebook-imagestream.yaml

      - name: Configure Git
        run: |
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git config --global user.name "GitHub Actions"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add notebook-images/base/minimal-notebook-imagestream.yaml
          git commit -m "new commit"
          git push origin ${{ inputs.branch }}




      # - name: Update the minimal Image Stream tag [0]
      #   shell: bash
      #   run: |
      #     # Reads the first image tag of the image stream
      #     tag=$(yq '.spec.tags[0].from.name' notebook-images/base/minimal-notebook-imagestream.yaml | tr -d '"')

      #     # Fetch the image in digest format using image tag name from quay.io
      #     digest=$(skopeo inspect docker://$tag | jq .Digest | sed 's/sha256/quay.io\/rh_ee_atheodor\/notebooks@sha256/g')

      #     # Fetch the target branch
      #     git fetch origin release-a

      #     # Switch to the target branch
      #     git checkout release-a

      #     # Modifies the yaml file from the release branch with the new weekly digest
      #     yq -i -Y '.spec.tags[0].from.name = "'"${digest//\"/}"'"' notebook-images/base/minimal-notebook-imagestream.yaml

      #     # Commit the changes
      #     git add notebook-images/base/minimal-notebook-imagestream.yaml
      #     git commit -m "Update file"

      #     # Push the changes to the target branch
      #     git push origin release-a

      # - name: Reads the first image tag
      #   shell: bash
      #   id: tag
      #   run: echo "tag=$(yq '.spec.tags[0].from.name' notebook-images/base/minimal-notebook-imagestream.yaml | tr -d '"')" >> ${GITHUB_OUTPUT}



            # - name: Fetch the image in digest format using image tag name from quay.io
      #   shell: bash
      #   env:
      #     TAG: ${{ steps.tag.outputs.tag }}
      #   id: digest
      #   run: echo "digest=$(skopeo inspect docker://${{ env.TAG }} | jq .Digest | sed 's/sha256/quay.io\/rh_ee_atheodor\/notebooks@sha256/g')" >> ${GITHUB_OUTPUT}


      # - name: Checkout release branch 
      #   uses: actions/checkout@v3
      #   with:
      #     ref: release-a

      # - name: Modifies the yaml file from the release branch with the new weekly digest
      #   shell: bash
      #   env:
      #     DIGEST: ${{ steps.digest.outputs.digest }}
      #   run: |
       
      #    git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #    git config --global user.name "GitHub Actions"
        
      #    # Fetch the target branch
      #    git fetch origin release-a

      #    yq e '.spec.tags[0].from.name = "'"$(echo ${{ env.DIGEST }} | sed 's/\"/\//g')"'"' -i notebook-images/base/minimal-notebook-imagestream.yaml

      #    # Commit the changes
      #    git add notebook-images/base/minimal-notebook-imagestream.yaml
      #    git commit -m "Update file"

      #    # Push the changes to the target branch
      #    git push origin release-a

      # - name: Checkout main branch again
      #   uses: actions/checkout@v3
      #   with:
      #     ref: main
